---
title: "P8130_hw4_cz2493"
author: "CHUHAN"
date: "10/25/2017"
output: html_document
---

### problem 2
##Part 1
```{r,message=FALSE,warning= FALSE}
library(tidyverse)
library(haven)
library(readxl)
library(janitor)
library(Hmisc)
library(ggthemes)
data_pols = read_csv("../data/fivethirtyeight_datasets/pols-month.csv") %>% 
clean_names() %>%
select(date = mon,everything()) 
data_pols = mutate(data_pols,
date = lubridate::floor_date(data_pols$date,"month"))

data_gdp = read_csv("../data/fivethirtyeight_datasets/GDP.csv") %>% clean_names() 
data_join = left_join(data_pols,data_gdp)

```

##Part 2
```{r,warning=FALSE}
data_join %>% 
  mutate(president = ifelse(prez_gop == 1, "gop","dem"),
         GDP = as.numeric(value)) %>% 
   select(., -prez_dem, -prez_gop) %>% 
   filter(!is.na(value)) %>% 
  ggplot(aes(x = date, y = GDP, color = president)) + 
  geom_point(aes(color = president), alpha = .75) + 
    xlab("date") + ylab("GDP") +
    scale_fill_hue(name = "President Party",
                   labels = c("Democratic Party", "Republican Party")) +
    ggtitle("The GDP value of each President Party") + 
    theme_bw()
```

